import { Link } from 'react-router-dom';
import { 
  DocumentMagnifyingGlassIcon, 
  ShieldCheckIcon, 
  DocumentDuplicateIcon,
  ClipboardDocumentCheckIcon,
  UserGroupIcon,
  LightBulbIcon,
  DocumentTextIcon
} from '@heroicons/react/24/outline';

const HomePage = () => {
  const features = [
    {
      name: 'Paper Analysis',
      description: 'Analyze research papers to extract insights on feasibility, innovation, and scalability.',
      icon: DocumentMagnifyingGlassIcon,
      path: '/paper-analysis',
    },
    {
      name: 'AI Detection',
      description: 'Check if text was generated by an AI system with confidence scores.',
      icon: ShieldCheckIcon,
      path: '/ai-detection',
    },
    {
      name: 'Paper Uniqueness',
      description: 'Evaluate the uniqueness of a research paper against existing literature.',
      icon: DocumentDuplicateIcon,
      path: '/paper-uniqueness',
    },
    {
      name: 'Paper Structuring',
      description: 'Format your research paper according to academic standards like IEEE, ACM, and APA.',
      icon: DocumentTextIcon,
      path: '/paper-structuring',
    },
    {
      name: 'Structure Check',
      description: 'Check how well a paper conforms to a specific academic format (IEEE, APA, etc.).',
      icon: ClipboardDocumentCheckIcon,
      path: '/paper-structure-check',
    },
    {
      name: 'Idea Rooms',
      description: 'Create rooms for organizing and judging uniqueness of research ideas in a pool.',
      icon: UserGroupIcon,
      path: '/rooms',
    },
  ];

  return (
    <div>
      <div className="relative py-12 sm:py-16 lg:py-20 px-4 sm:px-6 lg:px-8 text-center">
        <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
          <span className="block">Research Paper and Idea</span>
          <span className="block text-blue-600">Management Platform</span>
        </h1>
        <p className="mt-6 max-w-lg mx-auto text-xl text-gray-500 sm:max-w-3xl">
          Analyze research papers, detect AI-generated content, check uniqueness, 
          format papers to academic standards, and manage collaborative idea collection in one place.
        </p>
        <div className="mt-10 flex justify-center">
          <Link to="/paper-analysis" className="btn btn-primary">
            Analyze a Paper
          </Link>
          <Link to="/rooms" className="btn btn-secondary ml-4">
            View Rooms
          </Link>
        </div>
      </div>

      <div className="py-12 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
              Features
            </h2>
            <p className="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">
              Everything you need for research paper and idea management.
            </p>
          </div>

          <div className="mt-12">
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <Link 
                  key={feature.name}
                  to={feature.path}
                  className="card hover:shadow-lg transition-shadow"
                >
                  <div>
                    <feature.icon className="h-12 w-12 text-blue-500" />
                    <h3 className="mt-5 text-lg font-medium text-gray-900">{feature.name}</h3>
                    <p className="mt-2 text-base text-gray-500">{feature.description}</p>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="bg-gray-50 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
              Getting Started
            </h2>
            <p className="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">
              Begin by analyzing a paper or joining a collaborative room.
            </p>
          </div>

          <div className="mt-12 flex flex-col md:flex-row justify-center space-y-6 md:space-y-0 md:space-x-10">
            <div className="flex flex-col items-center">
              <div className="h-12 w-12 rounded-md bg-blue-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">1</span>
              </div>
              <h3 className="mt-6 text-lg font-medium text-gray-900">Upload a Paper</h3>
              <p className="mt-2 text-base text-gray-500 text-center max-w-xs">
                Upload a research paper for analysis, AI detection, or uniqueness checking.
              </p>
            </div>

            <div className="flex flex-col items-center">
              <div className="h-12 w-12 rounded-md bg-blue-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">2</span>
              </div>
              <h3 className="mt-6 text-lg font-medium text-gray-900">Join a Room</h3>
              <p className="mt-2 text-base text-gray-500 text-center max-w-xs">
                Enter a room with an access code or create your own space for organizing research ideas.
              </p>
            </div>

            <div className="flex flex-col items-center">
              <div className="h-12 w-12 rounded-md bg-blue-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">3</span>
              </div>
              <h3 className="mt-6 text-lg font-medium text-gray-900">Submit Ideas</h3>
              <p className="mt-2 text-base text-gray-500 text-center max-w-xs">
                Share and evaluate research ideas with automatic uniqueness checking.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage; 